"""Add challenges tables

Revision ID: 19462a0ecde8
Revises: 9f8feddef151
Create Date: 2026-02-11 14:07:28.294937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19462a0ecde8'
down_revision: Union[str, Sequence[str], None] = '9f8feddef151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('reward', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('challenge_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_completions_challenge_id'), 'challenge_completions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_completions_completion_date'), 'challenge_completions', ['completion_date'], unique=False)
    op.create_index(op.f('ix_challenge_completions_id'), 'challenge_completions', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_completions_user_id'), 'challenge_completions', ['user_id'], unique=False)
    op.create_table('user_challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('accepted_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenge_progress_challenge_id'), 'user_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenge_progress_id'), 'user_challenge_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_challenge_progress_user_id'), 'user_challenge_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_challenge_progress_user_id'), table_name='user_challenge_progress')
    op.drop_index(op.f('ix_user_challenge_progress_id'), table_name='user_challenge_progress')
    op.drop_index(op.f('ix_user_challenge_progress_challenge_id'), table_name='user_challenge_progress')
    op.drop_table('user_challenge_progress')
    op.drop_index(op.f('ix_challenge_completions_user_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_completion_date'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_challenge_id'), table_name='challenge_completions')
    op.drop_table('challenge_completions')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
