"""Initial migration

Revision ID: 4df3f35aa0ce
Revises: 
Create Date: 2026-02-10 15:04:57.517059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df3f35aa0ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_bn', sa.String(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('badge_icon', sa.String(), nullable=True),
    sa.Column('requirement_type', sa.String(), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_achievements_id'), 'habit_achievements', ['id'], unique=False)
    op.create_table('habit_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_bn', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_categories_id'), 'habit_categories', ['id'], unique=False)
    op.create_table('islamic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_bn', sa.String(), nullable=True),
    sa.Column('hijri_month', sa.Integer(), nullable=False),
    sa.Column('hijri_day', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('HOLIDAY', 'BATTLE', 'REVELATION', 'PROPHETIC', 'COMPANION', 'TREATY', 'SPECIAL', name='eventcategory'), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('full_story_en', sa.Text(), nullable=True),
    sa.Column('full_story_bn', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('color_code', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_islamic_events_id'), 'islamic_events', ['id'], unique=False)
    op.create_table('location_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('adjustment_days', sa.Integer(), nullable=True),
    sa.Column('method_description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name')
    )
    op.create_index(op.f('ix_location_settings_id'), 'location_settings', ['id'], unique=False)
    op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(), nullable=False),
    sa.Column('name_english', sa.String(), nullable=False),
    sa.Column('name_bengali', sa.String(), nullable=True),
    sa.Column('total_verses', sa.Integer(), nullable=False),
    sa.Column('revelation_type', sa.Enum('MECCAN', 'MEDINAN', name='revelationtype'), nullable=False),
    sa.Column('revelation_order', sa.Integer(), nullable=True),
    sa.Column('is_content_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surahs_id'), 'surahs', ['id'], unique=False)
    op.create_index(op.f('ix_surahs_surah_number'), 'surahs', ['surah_number'], unique=True)
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_bn', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('location_latitude', sa.String(), nullable=True),
    sa.Column('location_longitude', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('prayer_calculation_method', sa.String(), nullable=True),
    sa.Column('juristic_method', sa.String(), nullable=True),
    sa.Column('moon_sighting_location', sa.String(), nullable=True),
    sa.Column('calendar_view', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_habit_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_habits', sa.Integer(), nullable=True),
    sa.Column('completed_habits', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_habit_summary_id'), 'daily_habit_summary', ['id'], unique=False)
    op.create_index(op.f('ix_daily_habit_summary_summary_date'), 'daily_habit_summary', ['summary_date'], unique=False)
    op.create_index(op.f('ix_daily_habit_summary_user_id'), 'daily_habit_summary', ['user_id'], unique=False)
    op.create_table('habit_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_habits_created', sa.Integer(), nullable=True),
    sa.Column('active_habits', sa.Integer(), nullable=True),
    sa.Column('overall_completion_rate', sa.Integer(), nullable=True),
    sa.Column('best_habit_id', sa.Integer(), nullable=True),
    sa.Column('total_achievements', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_statistics_id'), 'habit_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_habit_statistics_user_id'), 'habit_statistics', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('prayer_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_times', sa.JSON(), nullable=True),
    sa.Column('track_jamaah', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_settings_id'), 'prayer_settings', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_settings_user_id'), 'prayer_settings', ['user_id'], unique=True)
    op.create_table('prayer_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_prayers_tracked', sa.Integer(), nullable=True),
    sa.Column('total_prayers_completed', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('fajr_completion_rate', sa.Integer(), nullable=True),
    sa.Column('dhuhr_completion_rate', sa.Integer(), nullable=True),
    sa.Column('asr_completion_rate', sa.Integer(), nullable=True),
    sa.Column('maghrib_completion_rate', sa.Integer(), nullable=True),
    sa.Column('isha_completion_rate', sa.Integer(), nullable=True),
    sa.Column('best_performing_prayer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_statistics_id'), 'prayer_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_statistics_user_id'), 'prayer_statistics', ['user_id'], unique=True)
    op.create_table('prayer_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('fajr_streak', sa.Integer(), nullable=True),
    sa.Column('dhuhr_streak', sa.Integer(), nullable=True),
    sa.Column('asr_streak', sa.Integer(), nullable=True),
    sa.Column('maghrib_streak', sa.Integer(), nullable=True),
    sa.Column('isha_streak', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_streaks_id'), 'prayer_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_streaks_user_id'), 'prayer_streaks', ['user_id'], unique=True)
    op.create_table('prayer_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('fajr', sa.Time(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.Column('dhuhr', sa.Time(), nullable=False),
    sa.Column('asr', sa.Time(), nullable=False),
    sa.Column('maghrib', sa.Time(), nullable=False),
    sa.Column('isha', sa.Time(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('calculation_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_times_id'), 'prayer_times', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_times_prayer_date'), 'prayer_times', ['prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_times_user_id'), 'prayer_times', ['user_id'], unique=False)
    op.create_table('prayer_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('fajr_completed', sa.Boolean(), nullable=True),
    sa.Column('fajr_jamaah', sa.Boolean(), nullable=True),
    sa.Column('fajr_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dhuhr_completed', sa.Boolean(), nullable=True),
    sa.Column('dhuhr_jamaah', sa.Boolean(), nullable=True),
    sa.Column('dhuhr_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asr_completed', sa.Boolean(), nullable=True),
    sa.Column('asr_jamaah', sa.Boolean(), nullable=True),
    sa.Column('asr_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maghrib_completed', sa.Boolean(), nullable=True),
    sa.Column('maghrib_jamaah', sa.Boolean(), nullable=True),
    sa.Column('maghrib_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('isha_completed', sa.Boolean(), nullable=True),
    sa.Column('isha_jamaah', sa.Boolean(), nullable=True),
    sa.Column('isha_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_tracking_id'), 'prayer_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_tracking_prayer_date'), 'prayer_tracking', ['prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_tracking_user_id'), 'prayer_tracking', ['user_id'], unique=False)
    op.create_table('productivity_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('most_productive_category', sa.String(), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_insights_id'), 'productivity_insights', ['id'], unique=False)
    op.create_index(op.f('ix_productivity_insights_insight_date'), 'productivity_insights', ['insight_date'], unique=False)
    op.create_index(op.f('ix_productivity_insights_user_id'), 'productivity_insights', ['user_id'], unique=False)
    op.create_table('qada_prayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fajr_count', sa.Integer(), nullable=True),
    sa.Column('dhuhr_count', sa.Integer(), nullable=True),
    sa.Column('asr_count', sa.Integer(), nullable=True),
    sa.Column('maghrib_count', sa.Integer(), nullable=True),
    sa.Column('isha_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qada_prayers_id'), 'qada_prayers', ['id'], unique=False)
    op.create_index(op.f('ix_qada_prayers_user_id'), 'qada_prayers', ['user_id'], unique=True)
    op.create_table('quran_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_surahs_completed', sa.Integer(), nullable=True),
    sa.Column('total_verses_read', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_bookmarks', sa.Integer(), nullable=True),
    sa.Column('last_read_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_statistics_id'), 'quran_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_quran_statistics_user_id'), 'quran_statistics', ['user_id'], unique=True)
    op.create_table('reading_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_surah_id', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('daily_verses_target', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_surah_id'], ['surahs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_goals_id'), 'reading_goals', ['id'], unique=False)
    op.create_index(op.f('ix_reading_goals_user_id'), 'reading_goals', ['user_id'], unique=False)
    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('last_verse_read', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_progress_id'), 'reading_progress', ['id'], unique=False)
    op.create_index(op.f('ix_reading_progress_surah_id'), 'reading_progress', ['surah_id'], unique=False)
    op.create_index(op.f('ix_reading_progress_user_id'), 'reading_progress', ['user_id'], unique=False)
    op.create_table('surah_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('brief_tafsir', sa.Text(), nullable=True),
    sa.Column('full_insights', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surah_content_id'), 'surah_content', ['id'], unique=False)
    op.create_index(op.f('ix_surah_content_surah_id'), 'surah_content', ['surah_id'], unique=True)
    op.create_table('task_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_tasks_created', sa.Integer(), nullable=True),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=True),
    sa.Column('active_tasks', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('high_priority_pending', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_statistics_id'), 'task_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_task_statistics_user_id'), 'task_statistics', ['user_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'ARCHIVED', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence_pattern', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='recurrencepattern'), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['habit_achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_dashboard_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_order', sa.JSON(), nullable=True),
    sa.Column('visible_widgets', sa.JSON(), nullable=True),
    sa.Column('layout_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dashboard_preferences_id'), 'user_dashboard_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_dashboard_preferences_user_id'), 'user_dashboard_preferences', ['user_id'], unique=True)
    op.create_table('user_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tracking_type', sa.Enum('CHECKBOX', 'COUNTER', 'TIMER', name='trackingtype'), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['habit_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_habits_id'), 'user_habits', ['id'], unique=False)
    op.create_index(op.f('ix_user_habits_user_id'), 'user_habits', ['user_id'], unique=False)
    op.create_table('user_overall_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_performance_score', sa.Integer(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_overall_stats_id'), 'user_overall_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_overall_stats_user_id'), 'user_overall_stats', ['user_id'], unique=True)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=False),
    sa.Column('translation_english', sa.Text(), nullable=True),
    sa.Column('translation_bengali', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verses_id'), 'verses', ['id'], unique=False)
    op.create_index(op.f('ix_verses_surah_id'), 'verses', ['surah_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_id'), 'weekly_plans', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_week_start_date'), 'weekly_plans', ['week_start_date'], unique=False)
    op.create_table('daily_verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_date', sa.Date(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('reflection_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_verses_id'), 'daily_verses', ['id'], unique=False)
    op.create_index(op.f('ix_daily_verses_verse_date'), 'daily_verses', ['verse_date'], unique=True)
    op.create_table('habit_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['user_habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_streaks_habit_id'), 'habit_streaks', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_streaks_id'), 'habit_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_habit_streaks_user_id'), 'habit_streaks', ['user_id'], unique=False)
    op.create_table('habit_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('tracking_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('counter_value', sa.Integer(), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['user_habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_tracking_habit_id'), 'habit_tracking', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_tracking_id'), 'habit_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_habit_tracking_tracking_date'), 'habit_tracking', ['tracking_date'], unique=False)
    op.create_index(op.f('ix_habit_tracking_user_id'), 'habit_tracking', ['user_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.create_table('verse_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verse_bookmarks_id'), 'verse_bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_verse_bookmarks_user_id'), 'verse_bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_verse_bookmarks_verse_id'), 'verse_bookmarks', ['verse_id'], unique=False)
    op.create_table('verse_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verse_notes_id'), 'verse_notes', ['id'], unique=False)
    op.create_index(op.f('ix_verse_notes_user_id'), 'verse_notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_verse_notes_verse_id'), 'verse_notes', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_notes_verse_id'), table_name='verse_notes')
    op.drop_index(op.f('ix_verse_notes_user_id'), table_name='verse_notes')
    op.drop_index(op.f('ix_verse_notes_id'), table_name='verse_notes')
    op.drop_table('verse_notes')
    op.drop_index(op.f('ix_verse_bookmarks_verse_id'), table_name='verse_bookmarks')
    op.drop_index(op.f('ix_verse_bookmarks_user_id'), table_name='verse_bookmarks')
    op.drop_index(op.f('ix_verse_bookmarks_id'), table_name='verse_bookmarks')
    op.drop_table('verse_bookmarks')
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_habit_tracking_user_id'), table_name='habit_tracking')
    op.drop_index(op.f('ix_habit_tracking_tracking_date'), table_name='habit_tracking')
    op.drop_index(op.f('ix_habit_tracking_id'), table_name='habit_tracking')
    op.drop_index(op.f('ix_habit_tracking_habit_id'), table_name='habit_tracking')
    op.drop_table('habit_tracking')
    op.drop_index(op.f('ix_habit_streaks_user_id'), table_name='habit_streaks')
    op.drop_index(op.f('ix_habit_streaks_id'), table_name='habit_streaks')
    op.drop_index(op.f('ix_habit_streaks_habit_id'), table_name='habit_streaks')
    op.drop_table('habit_streaks')
    op.drop_index(op.f('ix_daily_verses_verse_date'), table_name='daily_verses')
    op.drop_index(op.f('ix_daily_verses_id'), table_name='daily_verses')
    op.drop_table('daily_verses')
    op.drop_index(op.f('ix_weekly_plans_week_start_date'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_verses_surah_id'), table_name='verses')
    op.drop_index(op.f('ix_verses_id'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_user_overall_stats_user_id'), table_name='user_overall_stats')
    op.drop_index(op.f('ix_user_overall_stats_id'), table_name='user_overall_stats')
    op.drop_table('user_overall_stats')
    op.drop_index(op.f('ix_user_habits_user_id'), table_name='user_habits')
    op.drop_index(op.f('ix_user_habits_id'), table_name='user_habits')
    op.drop_table('user_habits')
    op.drop_index(op.f('ix_user_dashboard_preferences_user_id'), table_name='user_dashboard_preferences')
    op.drop_index(op.f('ix_user_dashboard_preferences_id'), table_name='user_dashboard_preferences')
    op.drop_table('user_dashboard_preferences')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_statistics_user_id'), table_name='task_statistics')
    op.drop_index(op.f('ix_task_statistics_id'), table_name='task_statistics')
    op.drop_table('task_statistics')
    op.drop_index(op.f('ix_surah_content_surah_id'), table_name='surah_content')
    op.drop_index(op.f('ix_surah_content_id'), table_name='surah_content')
    op.drop_table('surah_content')
    op.drop_index(op.f('ix_reading_progress_user_id'), table_name='reading_progress')
    op.drop_index(op.f('ix_reading_progress_surah_id'), table_name='reading_progress')
    op.drop_index(op.f('ix_reading_progress_id'), table_name='reading_progress')
    op.drop_table('reading_progress')
    op.drop_index(op.f('ix_reading_goals_user_id'), table_name='reading_goals')
    op.drop_index(op.f('ix_reading_goals_id'), table_name='reading_goals')
    op.drop_table('reading_goals')
    op.drop_index(op.f('ix_quran_statistics_user_id'), table_name='quran_statistics')
    op.drop_index(op.f('ix_quran_statistics_id'), table_name='quran_statistics')
    op.drop_table('quran_statistics')
    op.drop_index(op.f('ix_qada_prayers_user_id'), table_name='qada_prayers')
    op.drop_index(op.f('ix_qada_prayers_id'), table_name='qada_prayers')
    op.drop_table('qada_prayers')
    op.drop_index(op.f('ix_productivity_insights_user_id'), table_name='productivity_insights')
    op.drop_index(op.f('ix_productivity_insights_insight_date'), table_name='productivity_insights')
    op.drop_index(op.f('ix_productivity_insights_id'), table_name='productivity_insights')
    op.drop_table('productivity_insights')
    op.drop_index(op.f('ix_prayer_tracking_user_id'), table_name='prayer_tracking')
    op.drop_index(op.f('ix_prayer_tracking_prayer_date'), table_name='prayer_tracking')
    op.drop_index(op.f('ix_prayer_tracking_id'), table_name='prayer_tracking')
    op.drop_table('prayer_tracking')
    op.drop_index(op.f('ix_prayer_times_user_id'), table_name='prayer_times')
    op.drop_index(op.f('ix_prayer_times_prayer_date'), table_name='prayer_times')
    op.drop_index(op.f('ix_prayer_times_id'), table_name='prayer_times')
    op.drop_table('prayer_times')
    op.drop_index(op.f('ix_prayer_streaks_user_id'), table_name='prayer_streaks')
    op.drop_index(op.f('ix_prayer_streaks_id'), table_name='prayer_streaks')
    op.drop_table('prayer_streaks')
    op.drop_index(op.f('ix_prayer_statistics_user_id'), table_name='prayer_statistics')
    op.drop_index(op.f('ix_prayer_statistics_id'), table_name='prayer_statistics')
    op.drop_table('prayer_statistics')
    op.drop_index(op.f('ix_prayer_settings_user_id'), table_name='prayer_settings')
    op.drop_index(op.f('ix_prayer_settings_id'), table_name='prayer_settings')
    op.drop_table('prayer_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_habit_statistics_user_id'), table_name='habit_statistics')
    op.drop_index(op.f('ix_habit_statistics_id'), table_name='habit_statistics')
    op.drop_table('habit_statistics')
    op.drop_index(op.f('ix_daily_habit_summary_user_id'), table_name='daily_habit_summary')
    op.drop_index(op.f('ix_daily_habit_summary_summary_date'), table_name='daily_habit_summary')
    op.drop_index(op.f('ix_daily_habit_summary_id'), table_name='daily_habit_summary')
    op.drop_table('daily_habit_summary')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_table('task_categories')
    op.drop_index(op.f('ix_surahs_surah_number'), table_name='surahs')
    op.drop_index(op.f('ix_surahs_id'), table_name='surahs')
    op.drop_table('surahs')
    op.drop_index(op.f('ix_location_settings_id'), table_name='location_settings')
    op.drop_table('location_settings')
    op.drop_index(op.f('ix_islamic_events_id'), table_name='islamic_events')
    op.drop_table('islamic_events')
    op.drop_index(op.f('ix_habit_categories_id'), table_name='habit_categories')
    op.drop_table('habit_categories')
    op.drop_index(op.f('ix_habit_achievements_id'), table_name='habit_achievements')
    op.drop_table('habit_achievements')
    # ### end Alembic commands ###
