"""Add streak tracking to challenges

Revision ID: 824e18d2d512
Revises: 19462a0ecde8
Create Date: 2026-02-11 14:25:53.619476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824e18d2d512'
down_revision: Union[str, Sequence[str], None] = '19462a0ecde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_challenge_progress', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('user_challenge_progress', sa.Column('last_completion_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_challenge_progress', 'last_completion_date')
    op.drop_column('user_challenge_progress', 'current_streak')
    # ### end Alembic commands ###
