"""change_prayer_times_to_string

Revision ID: 9f8feddef151
Revises: 4df3f35aa0ce
Create Date: 2026-02-11 00:58:50.318719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8feddef151'
down_revision: Union[str, Sequence[str], None] = '4df3f35aa0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prayer_times', 'fajr',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'sunrise',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'dhuhr',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'asr',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'maghrib',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'isha',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prayer_times', 'isha',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'maghrib',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'asr',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'dhuhr',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'sunrise',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('prayer_times', 'fajr',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
