"""Add challenge features: categories, progression, notifications, grace days

Revision ID: 0fb79eee9343
Revises: 824e18d2d512
Create Date: 2026-02-11 14:57:10.109807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb79eee9343'
down_revision: Union[str, Sequence[str], None] = '824e18d2d512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('category', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('required_difficulty', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('notification_time', sa.String(), nullable=True))
    op.add_column('user_challenge_progress', sa.Column('max_streak', sa.Integer(), nullable=True))
    op.add_column('user_challenge_progress', sa.Column('is_unlocked', sa.Boolean(), nullable=True))
    op.add_column('user_challenge_progress', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_challenge_progress', sa.Column('grace_day_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_challenge_progress', 'grace_day_used')
    op.drop_column('user_challenge_progress', 'notification_enabled')
    op.drop_column('user_challenge_progress', 'is_unlocked')
    op.drop_column('user_challenge_progress', 'max_streak')
    op.drop_column('challenges', 'notification_time')
    op.drop_column('challenges', 'required_difficulty')
    op.drop_column('challenges', 'category')
    # ### end Alembic commands ###
